EMOTICONS = {':‑\\)': 'happy face or smiley',
 ':\\)': 'happy face or smiley',
 ':-\\]': 'happy face or smiley',
 ':\\]': 'happy face or smiley',
 ':-3': 'happy face smiley',
 ':3': 'happy face smiley',
 ':->': 'happy face smiley',
 ':>': 'happy face smiley',
 '8-\\)': 'happy face smiley',
 ':o\\)': 'happy face smiley',
 ':-\\}': 'happy face smiley',
 ':\\}': 'happy face smiley',
 ':-\\)': 'happy face smiley',
 ':c\\)': 'happy face smiley',
 ':\\^\\)': 'happy face smiley',
 '=\\]': 'happy face smiley',
 '=\\)': 'happy face smiley',
 ':‑D': 'laughing, big grin or laugh with glasses',
 ':D': 'laughing, big grin or laugh with glasses',
 '8‑D': 'laughing, big grin or laugh with glasses',
 '8D': 'laughing, big grin or laugh with glasses',
 'X‑D': 'laughing, big grin or laugh with glasses',
 'XD': 'laughing, big grin or laugh with glasses',
 '=D': 'laughing, big grin or laugh with glasses',
 '=3': 'laughing, big grin or laugh with glasses',
 'B\\^D': 'laughing, big grin or laugh with glasses',
 ':-\\)\\)': 'very happy',
 ':‑\\(': 'frown, sad, andry or pouting',
 ':-\\(': 'frown, sad, andry or pouting',
 ':\\(': 'frown, sad, andry or pouting',
 ':‑c': 'frown, sad, andry or pouting',
 ':c': 'frown, sad, andry or pouting',
 ':‑<': 'frown, sad, andry or pouting',
 ':<': 'frown, sad, andry or pouting',
 ':‑\\[': 'frown, sad, andry or pouting',
 ':\\[': 'frown, sad, andry or pouting',
 ':-\\|\\|': 'frown, sad, andry or pouting',
 '>:\\[': 'frown, sad, andry or pouting',
 ':\\{': 'frown, sad, andry or pouting',
 ':@': 'frown, sad, andry or pouting',
 '>:\\(': 'frown, sad, andry or pouting',
 ":'‑\\(": 'crying',
 ":'\\(": 'crying',
 ":'‑\\)": 'tears of happiness',
 ":'\\)": 'tears of happiness',
 "D‑':": 'horror',
 'D:<': 'disgust',
 'D:': 'sadness',
 'D8': 'great dismay',
 'D;': 'great dismay',
 'D=': 'great dismay',
 'DX': 'great dismay',
 ':‑O': 'surprise',
 ':O': 'surprise',
 ':‑o': 'surprise',
 ':o': 'surprise',
 ':-0': 'shock',
 '8‑0': 'yawn',
 '>:O': 'yawn',
 ':-\\*': 'kiss',
 ':\\*': 'kiss',
 ':X': 'kiss',
 ';‑\\)': 'wink or smirk',
 ';\\)': 'wink or smirk',
 '\\*-\\)': 'wink or smirk',
 '\\*\\)': 'wink or smirk',
 ';‑\\]': 'wink or smirk',
 ';\\]': 'wink or smirk',
 ';\\^\\)': 'wink or smirk',
 ':‑,': 'wink or smirk',
 ';D': 'wink or smirk',
 ':‑P': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 ':P': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 'X‑P': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 'XP': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 ':‑Þ': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 ':Þ': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 ':b': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 'd:': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 '=p': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 '>:P': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 ':‑/': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':/': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':-[.]': 'skeptical, annoyed, undecided, uneasy or hesitant',
 '>:[(\\\\)]': 'skeptical, annoyed, undecided, uneasy or hesitant',
 '>:/': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':[(\\\\)]': 'skeptical, annoyed, undecided, uneasy or hesitant',
 '=/': 'skeptical, annoyed, undecided, uneasy or hesitant',
 '=[(\\\\)]': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':L': 'skeptical, annoyed, undecided, uneasy or hesitant',
 '=L': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':S': 'skeptical, annoyed, undecided, uneasy or hesitant',
 ':‑\\|': 'straight face',
 ':\\|': 'straight face',
 ':$': 'embarrassed or blushing',
 ':‑x': 'sealed lips or wearing braces or tongue-tied',
 ':x': 'sealed lips or wearing braces or tongue-tied',
 ':‑#': 'sealed lips or wearing braces or tongue-tied',
 ':#': 'sealed lips or wearing braces or tongue-tied',
 ':‑&': 'sealed lips or wearing braces or tongue-tied',
 ':&': 'sealed lips or wearing braces or tongue-tied',
 'O:‑\\)': 'angel, saint or innocent',
 'O:\\)': 'angel, saint or innocent',
 '0:‑3': 'angel, saint or innocent',
 '0:3': 'angel, saint or innocent',
 '0:‑\\)': 'angel, saint or innocent',
 '0:\\)': 'angel, saint or innocent',
 ':‑b': 'tongue sticking out, cheeky, playful or blowing a raspberry',
 '0;\\^\\)': 'angel, saint or innocent',
 '>:‑\\)': 'evil or devilish',
 '>:\\)': 'evil or devilish',
 '\\}:‑\\)': 'evil or devilish',
 '\\}:\\)': 'evil or devilish',
 '3:‑\\)': 'evil or devilish',
 '3:\\)': 'evil or devilish',
 '>;\\)': 'evil or devilish',
 '\\|;‑\\)': 'cool',
 '\\|‑O': 'bored',
 ':‑J': 'tongue-in-cheek',
 '#‑\\)': 'party all night',
 '%‑\\)': 'drunk or confused',
 '%\\)': 'drunk or confused',
 ':-###..': 'being sick',
 ':###..': 'being sick',
 '<:‑\\|': 'dump',
 '\\(>_<\\)': 'troubled',
 '\\(>_<\\)>': 'troubled',
 "\\(';'\\)": 'baby',
 '\\(\\^\\^>``': 'nervous or embarrassed or troubled or shy or sweat drop',
 '\\(\\^_\\^;\\)': 'nervous or embarrassed or troubled or shy or sweat drop',
 '\\(-_-;\\)': 'nervous or embarrassed or troubled or shy or sweat drop',
 '\\(~_~;\\) \\(・\\.・;\\)': 'nervous or embarrassed or troubled or shy or sweat drop',
 '\\(-_-\\)zzz': 'sleeping',
 '\\(\\^_-\\)': 'wink',
 '\\(\\(\\+_\\+\\)\\)': 'confused',
 '\\(\\+o\\+\\)': 'confused',
 '\\(o\\|o\\)': 'ultraman',
 '\\^_\\^': 'joyful',
 '\\(\\^_\\^\\)/': 'joyful',
 '\\(\\^O\\^\\)／': 'joyful',
 '\\(\\^o\\^\\)／': 'joyful',
 '\\(__\\)': 'kowtow as a sign of respect, or dogeza for apology',
 '_\\(\\._\\.\\)_': 'kowtow as a sign of respect, or dogeza for apology',
 '<\\(_ _\\)>': 'kowtow as a sign of respect, or dogeza for apology',
 '<m\\(__\\)m>': 'kowtow as a sign of respect, or dogeza for apology',
 'm\\(__\\)m': 'kowtow as a sign of respect, or dogeza for apology',
 'm\\(_ _\\)m': 'kowtow as a sign of respect, or dogeza for apology',
 "\\('_'\\)": 'sad or crying',
 '\\(/_;\\)': 'sad or crying',
 '\\(T_T\\) \\(;_;\\)': 'sad or crying',
 '\\(;_;': 'sad of crying',
 '\\(;_:\\)': 'sad or crying',
 '\\(;O;\\)': 'sad or crying',
 '\\(:_;\\)': 'sad or crying',
 '\\(ToT\\)': 'sad or crying',
 ';_;': 'sad or crying',
 ';-;': 'sad or crying',
 ';n;': 'sad or crying',
 ';;': 'sad or crying',
 'Q\\.Q': 'sad or crying',
 'T\\.T': 'sad or crying',
 'QQ': 'sad or crying',
 'Q_Q': 'sad or crying',
 '\\(-\\.-\\)': 'shame',
 '\\(-_-\\)': 'shame',
 '\\(一一\\)': 'shame',
 '\\(；一_一\\)': 'shame',
 '\\(=_=\\)': 'tired',
 '\\(=\\^\\·\\^=\\)': 'cat',
 '\\(=\\^\\·\\·\\^=\\)': 'cat',
 '=_\\^=\t': 'cat',
 '\\(\\.\\.\\)': 'looking down',
 '\\(\\._\\.\\)': 'looking down',
 '\\^m\\^': 'giggling with hand covering mouth',
 '\\(\\・\\・?': 'confusion',
 '\\(?_?\\)': 'confusion',
 '>\\^_\\^<': 'normal laugh',
 '<\\^!\\^>': 'normal laugh',
 '\\^/\\^': 'normal laugh',
 '\\（\\*\\^_\\^\\*）': 'normal laugh',
 '\\(\\^<\\^\\) \\(\\^\\.\\^\\)': 'normal laugh',
 '\\(^\\^\\)': 'normal laugh',
 '\\(\\^\\.\\^\\)': 'normal laugh',
 '\\(\\^_\\^\\.\\)': 'normal laugh',
 '\\(\\^_\\^\\)': 'normal laugh',
 '\\(\\^\\^\\)': 'normal laugh',
 '\\(\\^J\\^\\)': 'normal laugh',
 '\\(\\*\\^\\.\\^\\*\\)': 'normal laugh',
 '\\(\\^—\\^\\）': 'normal laugh',
 '\\(#\\^\\.\\^#\\)': 'normal laugh',
 '\\（\\^—\\^\\）': 'waving',
 '\\(;_;\\)/~~~': 'waving',
 '\\(\\^\\.\\^\\)/~~~': 'waving',
 '\\(-_-\\)/~~~ \\($\\·\\·\\)/~~~': 'waving',
 '\\(T_T\\)/~~~': 'waving',
 '\\(ToT\\)/~~~': 'waving',
 '\\(\\*\\^0\\^\\*\\)': 'excited',
 '\\(\\*_\\*\\)': 'amazed',
 '\\(\\*_\\*;': 'amazed',
 '\\(\\+_\\+\\) \\(@_@\\)': 'amazed',
 '\\(\\*\\^\\^\\)v': 'laughing,cheerful',
 '\\(\\^_\\^\\)v': 'laughing,cheerful',
 '\\(\\(d[-_-]b\\)\\)': 'headphones,listening to music',
 '\\(-"-\\)': 'worried',
 '\\(ーー;\\)': 'worried',
 '\\(\\^0_0\\^\\)': 'eyeglasses',
 '\\(\\＾ｖ\\＾\\)': 'happy',
 '\\(\\＾ｕ\\＾\\)': 'happy',
 '\\(\\^\\)o\\(\\^\\)': 'happy',
 '\\(\\^O\\^\\)': 'happy',
 '\\(\\^o\\^\\)': 'happy',
 '\\)\\^o\\^\\(': 'happy',
 ':O o_O': 'surprised',
 'o_0': 'surprised',
 'o\\.O': 'surpised',
 '\\(o\\.o\\)': 'surprised',
 'oO': 'surprised',
 '\\(\\*￣m￣\\)': 'dissatisfied',
 '\\(‘A`\\)': 'snubbed or deflated'}